name: CI

env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1
  COMPOSE_FILE: docker-compose.yml

on:
  pull_request:
    branches: ["master", "main"]
    paths-ignore: ["docs/**"]

  push:
    branches: ["master", "main"]
    paths-ignore: ["docs/**"]

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  linter:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12.4"]
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1

  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [jupyterhub, nginx, restic_backup]
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Check if COMPOSE_FILE is set
        run: |
          if [[ -z "${{ env.COMPOSE_FILE }}" ]]; then
            echo "COMPOSE_FILE is not set in the environment variables."
            exit 1
          fi

      - name: Check if SECRETS_ENV secret is set
        run: |
          if [[ -z "${{ secrets.SECRETS_ENV }}" ]]; then
            echo "SECRETS_ENV is not set in the secrets."
            exit 1
          fi

      - name: Create .envs/.env file
        run: |
          mkdir -p .envs
          echo "${{ secrets.SECRETS_ENV }}" > .envs/.env

      - name: Build the Stack
        run: docker compose -f ${{ env.COMPOSE_FILE }} build ${{ matrix.service }}

      - name: Tear down the Stack
        run: docker compose -f ${{ env.COMPOSE_FILE }} down
